version: '3.9'

networks:
  scraper-net:
    driver: bridge

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: professy
    volumes:
      - mongo-data:/data/db
    networks:
      - scraper-net

  app:
    build: .
    container_name: scraper-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/professy
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_CX: ${GOOGLE_CX}
    depends_on:
      - mongo
    networks:
      - scraper-net
    command: npm run start:prod

volumes:
  mongo-data:
